services:
  traefik:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.${APP_ENV}.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic/http.${APP_ENV}.yml:/etc/traefik/dynamic/http.yml:ro
      - ./dynamic/tls.${APP_ENV}.yml:/etc/traefik/dynamic/tls.yml:ro
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro