services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - conversion_app
    command:
      - /bin/sh
      - -c
      - |
        chmod 600 /acme.json && \
        traefik --configFile=/etc/traefik/traefik.yml
    volumes:
      - ./traefik.${APP_ENV}.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic/http.${APP_ENV}.yml:/etc/traefik/dynamic/http.yml:ro
      - ./dynamic/tls.${APP_ENV}.yml:/etc/traefik/dynamic/tls.yml:ro
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro


networks:
  conversion_app:
    name: conversion_app
    external: true