api:
  insecure: true
  dashboard: true

log:
  level: DEBUG


entryPoints:
  http:
    address: ":80"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true