entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: gertyn07@gmail.com
      storage: /acme.json
      dnsChallenge:
        provider: "cloudflare"
        resolvers:
          - "8.8.8.8:53"