entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

api:
  insecure: true
  dashboard: true

log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: gertyn07@gmail.com
      storage: /acme.json
      tlsChallenge: {}