http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
    dashboard-ip-whitelist:
      ipWhiteList:
        sourceRange:
          - "5.136.87.206/32" # my
          - "79.132.136.31/32" # vpn
          - "127.0.0.1/32"

  routers:
    dashboard:
      rule: "Host(`${DASHBOARD_SUBDOMAIN?}.${BASE_DOMAIN?}`)"
      entryPoints:
        - https
      middlewares:
        - dashboard-ip-whitelist
      service: api@internal
      tls:
        certResolver: letsencrypt