tls:
  options:
    default:
      minVersion: VersionTLS12
  stores:
    default:
      defaultCertificate:
        certFile: /etc/letsencrypt/live/nambapp.ru/chain.pem
        keyFile: /etc/letsencrypt/live/nambapp.ru/privkey.pem
