tls:
  options:
    default:
      minVersion: VersionTLS12
  stores:
    default:
      defaultCertificate:
        certFile: /etc/letsencrypt/live/nambapp.ru/fullchain.pem
        keyFile: /etc/letsencrypt/live/nambapp.ru/privkey.pem
      certificates:
        - certFile: /etc/letsencrypt/live/nambapp.ru/fullchain.pem
          keyFile: /etc/letsencrypt/live/nambapp.ru/privkey.pem
          caFiles:
              - /etc/letsencrypt/live/nambapp.ru/chain.pem
